// Author: Kaviru Hapuarachchi
// GitHub: https://github.com/kavirubc
// Created: 2026-02-04

package steps

import (
	"fmt"
	"log"
	"strings"

	"github.com/similigh/simili-bot/internal/core/pipeline"
	"github.com/similigh/simili-bot/internal/integrations/github"
)

// CommandHandler processes bot commands like /undo.
type CommandHandler struct {
	gh *github.Client
}

// NewCommandHandler creates a new command handler step.
func NewCommandHandler(deps *pipeline.Dependencies) *CommandHandler {
	return &CommandHandler{
		gh: deps.GitHub,
	}
}

// Name returns the step name.
func (s *CommandHandler) Name() string {
	return "command_handler"
}

// isBotComment checks whether a comment body was generated by Simili-Bot.
// It checks for the hidden HTML marker (preferred), the legacy emoji marker,
// and the plain-text header as a fallback.
func isBotComment(body string) bool {
	return strings.Contains(body, "<!-- simili-bot-report -->") ||
		strings.Contains(body, "🤖 Simili Triage Report") ||
		strings.Contains(body, "### Simili Triage Report")
}

// Run checks for commands in issue comments.
func (s *CommandHandler) Run(ctx *pipeline.Context) error {
	// Handle specific commands in comment events
	if ctx.Issue.EventType == "issue_comment" || ctx.Issue.EventType == "pr_comment" {
		body := strings.TrimSpace(ctx.Issue.CommentBody)
		if body == "" {
			return pipeline.ErrSkipPipeline
		}

		// Self-prevention: Ignore bot's own reports even if using PAT.
		// Uses multiple markers for backward compatibility (see isBotComment).
		if isBotComment(body) {
			log.Printf("[command_handler] Detected bot's own comment on #%d, skipping pipeline", ctx.Issue.Number)
			return pipeline.ErrSkipPipeline
		}

		// Also skip if the comment author looks like a bot (belt-and-suspenders).
		if isBotAuthor(ctx.Issue.CommentAuthor, ctx.Config.BotUsers) {
			log.Printf("[command_handler] Detected bot author %q on #%d, skipping pipeline",
				ctx.Issue.CommentAuthor, ctx.Issue.Number)
			return pipeline.ErrSkipPipeline
		}

		command := strings.ToLower(body)

		// Check for @simili-bot trigger (Claude Code integration).
		// This runs before slash-commands so "@simili-bot /undo" doesn't accidentally undo.
		if strings.Contains(command, "@simili-bot") {
			return s.handleClaudeCodeTrigger(ctx, body)
		}

		if strings.HasPrefix(command, "/") {
			log.Printf("[command_handler] Processing command: %s", command)
			switch {
			case strings.HasPrefix(command, "/undo"):
				return s.handleUndo(ctx)
			default:
				log.Printf("[command_handler] Unknown command: %s", command)
			}
			// After processing a command, we might want to continue to ActionExecutor,
			// but we definitely want to skip the intermediate triage steps.
			// However, since we can't "jump", we let it return nil and other steps must skip comments.
			return nil
		}

		// Not a command? Skip the entire triage pipeline for comments.
		return pipeline.ErrSkipPipeline
	}

	// For issue, pull_request, and pr_comment events, check for Claude Code
	// label triggers and then scan comment history for transfer loops.
	if ctx.Issue.EventType == "issues" || ctx.Issue.EventType == "pull_request" || ctx.Issue.EventType == "pr_comment" {
		// Claude Code label-based features (only if claude_code is enabled).
		if ctx.Config != nil && ctx.Config.ClaudeCode.Enabled != nil && *ctx.Config.ClaudeCode.Enabled {
			if err := s.checkClaudeCodeLabelTriggers(ctx); err != nil {
				return err
			}
		}
		return s.analyzeHistoryForLoops(ctx)
	}

	// Scheduled / workflow_dispatch events → maintenance.
	if ctx.Issue.EventType == "schedule" || ctx.Issue.EventType == "workflow_dispatch" {
		if ctx.Config != nil && ctx.Config.ClaudeCode.Enabled != nil && *ctx.Config.ClaudeCode.Enabled &&
			ctx.Config.ClaudeCode.Maintenance.Enabled != nil && *ctx.Config.ClaudeCode.Maintenance.Enabled {
			return s.handleMaintenanceTrigger(ctx)
		}
	}

	return nil
}

// checkClaudeCodeLabelTriggers checks if the current event matches any
// label-based Claude Code feature triggers.
func (s *CommandHandler) checkClaudeCodeLabelTriggers(ctx *pipeline.Context) error {
	cc := ctx.Config.ClaudeCode

	// Issue Implementation: issue labeled with trigger label (e.g., "implement").
	if ctx.Issue.EventType == "issues" && ctx.Issue.EventAction == "labeled" {
		if cc.IssueImplement.Enabled != nil && *cc.IssueImplement.Enabled {
			if hasLabel(ctx.Issue.Labels, cc.IssueImplement.TriggerLabel) {
				return s.handleIssueImplementTrigger(ctx)
			}
		}
	}

	// PR label triggers: security review and review checklist.
	if ctx.Issue.EventType == "pull_request" && ctx.Issue.EventAction == "labeled" {

		// Security Review: PR labeled with trigger label (e.g., "security-review").
		if cc.SecurityReview.Enabled != nil && *cc.SecurityReview.Enabled {
			if hasLabel(ctx.Issue.Labels, cc.SecurityReview.TriggerLabel) {
				return s.handleSecurityReviewTrigger(ctx)
			}
		}

		// Review Checklist: PR labeled with trigger label (e.g., "review-checklist").
		if cc.ReviewChecklist.Enabled != nil && *cc.ReviewChecklist.Enabled {
			if hasLabel(ctx.Issue.Labels, cc.ReviewChecklist.TriggerLabel) {
				return s.handleReviewChecklistTrigger(ctx)
			}
		}
	}

	// Doc Sync: PR opened/updated that changes watched paths.
	if ctx.Issue.EventType == "pull_request" &&
		(ctx.Issue.EventAction == "opened" || ctx.Issue.EventAction == "synchronize") {
		if cc.DocSync.Enabled != nil && *cc.DocSync.Enabled && len(cc.DocSync.WatchPaths) > 0 {
			// Changed files are passed via metadata from the event payload.
			if changedFiles, ok := ctx.Metadata["changed_files"].([]string); ok && len(changedFiles) > 0 {
				matched := matchesDocSyncPaths(changedFiles, cc.DocSync.WatchPaths)
				if len(matched) > 0 {
					return s.handleDocSyncTrigger(ctx, matched)
				}
			}
		}
	}

	return nil
}

// hasLabel checks if the given label exists in the issue's label list.
func hasLabel(labels []string, target string) bool {
	for _, l := range labels {
		if strings.EqualFold(l, target) {
			return true
		}
	}
	return false
}

// analyzeHistoryForLoops checks history for undo commands and previous transfers to preventing loops
func (s *CommandHandler) analyzeHistoryForLoops(ctx *pipeline.Context) error {
	if s.gh == nil {
		return nil
	}

	// Fetch recent comments
	comments, _, err := s.gh.ListComments(ctx.Ctx, ctx.Issue.Org, ctx.Issue.Repo, ctx.Issue.Number, nil)
	if err != nil {
		log.Printf("[command_handler] Failed to list comments: %v", err)
		return nil // Non-fatal
	}

	var blockedTargets []string

	// Analyze comments
	for _, c := range comments {
		body := strings.TrimSpace(c.GetBody())

		// Check for /undo command
		if strings.EqualFold(body, "/undo") {
			log.Printf("[command_handler] Found /undo in history. Blocking auto-transfer.")
			ctx.Metadata["transfer_blocked"] = true
		}

		// Check for previous transfers (hot-potato loop prevention)
		if isBotComment(body) && strings.Contains(body, "Transferred from") {
			sourceRepo := s.extractSourceRepo(body)
			if sourceRepo != "" {
				log.Printf("[command_handler] Found previous transfer from %s. Blocking return transfer.", sourceRepo)
				blockedTargets = append(blockedTargets, sourceRepo)
			}
		}
	}

	if len(blockedTargets) > 0 {
		ctx.Metadata["blocked_targets"] = blockedTargets
	}

	return nil
}

// handleUndo reverses a previous transfer.
func (s *CommandHandler) handleUndo(ctx *pipeline.Context) error {
	if s.gh == nil {
		return fmt.Errorf("GitHub client required for undo command")
	}

	log.Printf("[command_handler] Handling /undo for issue #%d", ctx.Issue.Number)

	// To undo, we need to find where this issue came from.
	// We look for Simili-Bot's triage report which contains the source info.
	comments, _, err := s.gh.ListComments(ctx.Ctx, ctx.Issue.Org, ctx.Issue.Repo, ctx.Issue.Number, nil)
	if err != nil {
		return fmt.Errorf("failed to list comments for undo: %w", err)
	}

	var sourceRepo string
	for _, c := range comments {
		body := c.GetBody()
		if isBotComment(body) && strings.Contains(body, "Transferred from") {
			// Extract source repo from text like "Transferred from **similigh/event-integrator-core**"
			sourceRepo = s.extractSourceRepo(body)
			if sourceRepo != "" {
				break
			}
		}
	}

	if sourceRepo == "" {
		log.Printf("[command_handler] Could not determine source repository for /undo")
		return nil
	}

	log.Printf("[command_handler] Reversing transfer back to %s", sourceRepo)
	ctx.TransferTarget = sourceRepo
	ctx.Metadata["reverse_transfer"] = true

	// Professional Alert style
	ctx.Metadata["comment"] = fmt.Sprintf(`> [!NOTE]
> **Transfer Reverted**
> Issue moved back to **%s** (requested by @%s).`, sourceRepo, ctx.Issue.CommentAuthor)

	return nil
}

// extractSourceRepo pulls the repo name out of the triage report body.
func (s *CommandHandler) extractSourceRepo(body string) string {
	// Simple marker-based extraction
	marker := "Transferred from **"
	start := strings.Index(body, marker)
	if start == -1 {
		// Try without bolding just in case
		marker = "Transferred from "
		start = strings.Index(body, marker)
		if start == -1 {
			return ""
		}
	}
	start += len(marker)

	end := strings.Index(body[start:], "**")
	if end == -1 {
		// If no closing bolding, try looking for space or newline
		end = strings.IndexAny(body[start:], " \n")
		if end == -1 {
			end = len(body[start:])
		}
	}

	return strings.TrimSpace(body[start : start+end])
}
