package steps

import (
	"context"
	"strings"
	"testing"

	"github.com/similigh/simili-bot/internal/core/config"
	"github.com/similigh/simili-bot/internal/core/pipeline"
	"github.com/similigh/simili-bot/internal/integrations/gemini"
)

func TestResponseBuilder_buildTriageSummary(t *testing.T) {
	// Setup
	deps := &pipeline.Dependencies{}
	builder := NewResponseBuilder(deps)

	// Create test context with necessary metadata
	ctx := &pipeline.Context{
		Ctx: context.Background(),
		Issue: &pipeline.Issue{
			Org:    "similigh",
			Repo:   "simili-bot",
			Number: 123,
			Title:  "Test Issue",
		},
		Config: &config.Config{
			Transfer: config.TransferConfig{
				MediumConfidence: 0.7,
			},
		},
		Metadata: make(map[string]interface{}),
		Result: &pipeline.Result{
			SuggestedLabels: []string{"bug", "backend", "urgent"},
		},
		SimilarIssues: []pipeline.SimilarIssue{
			{Title: "Similar 1", Number: 45, Similarity: 0.92, State: "closed", URL: "http://github.com/similigh/simili-bot/issues/45"},
		},
	}

	// Mock Quality Result
	ctx.Metadata["quality_result"] = &gemini.QualityResult{
		Score:       0.85,
		Assessment:  "excellent",
		Issues:      []string{},
		Suggestions: []string{"Add logs"},
	}

	// Mock Transfer Result (Router)
	ctx.Metadata["router_result"] = &gemini.RouterResult{
		BestMatch: &gemini.RepositoryRanking{
			Org:        "similigh",
			Repo:       "core-backend",
			Confidence: 0.95,
			Reasoning:  "It is backend code",
		},
	}

	// Run
	summary := builder.buildTriageSummary(ctx)

	// Verify crucial elements
	expectedElements := []string{
		"### Simili Triage Report",
		"> [!NOTE]",
		"**Quality Score: 8.5/10 (Excellent)**",
		"#### Classification",
		"| Category | Value |",
		"| :--- | :--- |",
		"| **Labels** | ![](https://img.shields.io/badge/bug-ff7300) ![](https://img.shields.io/badge/backend-000000) ![](https://img.shields.io/badge/urgent-ff7300) |",
		"Suggested: **similigh/core-backend** ![](https://img.shields.io/badge/confidence-95%25-ff7300)",
		"<details>",
		"<summary>Quality Improvements</summary>",
		"<summary>Similar Issues</summary>",
		"| 92% | [#45 Similar 1](http://github.com/similigh/simili-bot/issues/45) | Closed |",
		"<sub>Generated by [Simili Bot](https://github.com/similigh/simili-bot)</sub>",
	}

	for _, elem := range expectedElements {
		if !strings.Contains(summary, elem) {
			t.Errorf("Summary missing expected element: %s", elem)
			t.Logf("Generated Summary:\n%s", summary)
		}
	}
}

func TestResponseBuilder_buildTransferRow_CurrentRepo(t *testing.T) {
	deps := &pipeline.Dependencies{}
	builder := NewResponseBuilder(deps)

	ctx := &pipeline.Context{
		Issue:    &pipeline.Issue{Org: "similigh", Repo: "simili-bot"},
		Config:   &config.Config{Transfer: config.TransferConfig{MediumConfidence: 0.7}},
		Metadata: make(map[string]interface{}),
	}

	ctx.Metadata["router_result"] = &gemini.RouterResult{
		BestMatch: &gemini.RepositoryRanking{
			Org:        "similigh",
			Repo:       "simili-bot", // Same repo
			Confidence: 0.95,
		},
	}

	row := builder.buildTransferRow(ctx)

	if !strings.Contains(row, "✅ To check **similigh/simili-bot**") {
		t.Errorf("Expected 'Issue belongs in this repository' message, got: %s", row)
	}
}
